
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: mondzikd/io-lab-docker-ci-public:0.1
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    volumes:
      - .:/data
    entrypoint: redis-server --appendonly yes
    restart: always
